# Generated by Django 3.2.5 on 2021-11-28 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('surname', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('born', models.DateField()),
                ('died', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('administrator', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('street_name', models.CharField(max_length=100)),
                ('street_no', models.PositiveSmallIntegerField(null=True)),
                ('city', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('opening_monday', models.TimeField()),
                ('closing_monday', models.TimeField()),
                ('opening_tuesday', models.TimeField()),
                ('closing_tuesday', models.TimeField()),
                ('opening_wednesday', models.TimeField()),
                ('closing_wednesday', models.TimeField()),
                ('opening_thursday', models.TimeField()),
                ('closing_thursday', models.TimeField()),
                ('opening_friday', models.TimeField()),
                ('closing_friday', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('finished', models.BooleanField(default=False)),
                ('handled', models.BooleanField(default=False)),
                ('books', models.ManyToManyField(db_table='ordered_books', to='main.Book')),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.distributor')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('level', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('isbn', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('authors', models.ManyToManyField(db_table='title_author', to='main.Author')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.genre')),
            ],
        ),
        migrations.CreateModel(
            name='TitleInLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owned', models.BooleanField()),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.library')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.title')),
            ],
        ),
        migrations.CreateModel(
            name='TitleNotOwned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_count', models.PositiveSmallIntegerField(default=0)),
                ('title_in_library', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.titleinlibrary')),
                ('votes', models.ManyToManyField(blank=True, db_table='votes', to='main.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('ready', models.BooleanField(default=False)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.book')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.profile')),
                ('title_in_library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.titleinlibrary')),
            ],
        ),
        migrations.CreateModel(
            name='OrderTitleInLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.SmallIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.order')),
                ('title_in_library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.titleinlibrary')),
            ],
        ),
        migrations.CreateModel(
            name='Borrowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_from', models.DateField()),
                ('borrowed_to', models.DateField()),
                ('finished', models.BooleanField(default=False)),
                ('returned', models.BooleanField(default=False)),
                ('books', models.ManyToManyField(db_table='borrowed_books', to='main.Book')),
                ('collected', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collected', to='main.employee')),
                ('created', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created', to='main.employee')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.profile')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='title_in_library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.titleinlibrary'),
        ),
    ]
